name: DevOpsStudyApp CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    #1. Get Code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -la

    #2. Set up docker
      - name: Build Docker image
        run: docker build -t devops-study-app .

    #3. Run container test
      - name: Run container
        run: |
          docker run -d -p 80:80 --name app devops-study-app
          sleep 10
          docker ps -a
          docker logs app
          curl -v http://localhost:80 || exit 1

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/DevOpsStudyApp
            git pull origin main
            docker-compose down
            docker-compose up -d --build